export { default as Heading } from './Heading'
export { default as Label } from './Label'
export { default as Small } from './Small'
export { default as Status } from './Status'
export { default as Text } from './Text'
export { default as Paragraph } from './Paragraph'
