export { default as Error } from './src/Error'
export { default as Heading } from './src/Heading'
export { default as Label } from './src/Label'
export { default as Small } from './src/Small'
export { default as Status } from './src/Status'
export { default as Text } from './src/Text'
