export {
  AdminIcon,
  ArtistIcon,
  CheckIcon,
  ChevronDownIcon,
  CloseIcon,
  InboxIcon,
  LogoutIcon,
  SearchIcon,
  SynthAdminIconComponent,
  SynthAdminIconProps,
  SynthArtistIconComponent,
  SynthArtistIconProps,
  SynthCheckIconComponent,
  SynthCheckIconProps,
  SynthChevronDownIconComponent,
  SynthChevronDownIconProps,
  SynthCloseIconComponent,
  SynthCloseIconProps,
  SynthInboxIconComponent,
  SynthInboxIconProps,
  SynthLogoutIconComponent,
  SynthLogoutIconProps,
  SynthSearchIconComponent,
  SynthSearchIconProps,
} from './Icons'
