export { default as AdminIcon } from './AdminIcon'
export { default as ArtistIcon } from './ArtistIcon'
export { default as CheckIcon } from './CheckIcon'
export { default as InboxIcon } from './InboxIcon'
export { default as LogoutIcon } from './LogoutIcon'
