export const TOKEN_CATEGORY_COLOR = 'color'
export const TOKEN_CATEGORY_GLOBAL = 'global'
export const TOKEN_CATEGORY_POSITION = 'position'
export const TOKEN_CATEGORY_SIZE = 'size'
export const TOKEN_CATEGORY_SPACE = 'space'
export const TOKEN_CATEGORY_STYLE = 'style'
export const TOKEN_CATEGORY_TYPOGRAPHY = 'typography'

export const TOKEN_CATEGORIES = [
  TOKEN_CATEGORY_COLOR,
  TOKEN_CATEGORY_GLOBAL,
  TOKEN_CATEGORY_POSITION,
  TOKEN_CATEGORY_SIZE,
  TOKEN_CATEGORY_SPACE,
  TOKEN_CATEGORY_STYLE,
  TOKEN_CATEGORY_TYPOGRAPHY,
]

export const TOKEN_PROPERTY_BACKGROUND = 'background'
export const TOKEN_PROPERTY_BORDER = 'border'
export const TOKEN_PROPERTY_BOTTOM = 'bottom'
export const TOKEN_PROPERTY_COLOR = 'text'
export const TOKEN_PROPERTY_FONT_FAMILY = 'font'
export const TOKEN_PROPERTY_FONT_SIZE = 'size'
export const TOKEN_PROPERTY_HEIGHT = 'height'
export const TOKEN_PROPERTY_INDEX = 'index'
export const TOKEN_PROPERTY_LEFT = 'left'
export const TOKEN_PROPERTY_LINE_HEIGHT = 'lineHeight'
export const TOKEN_PROPERTY_MARGIN = 'margin'
export const TOKEN_PROPERTY_MAX_HEIGHT = 'maxHeight'
export const TOKEN_PROPERTY_MAX_WIDTH = 'maxWidth'
export const TOKEN_PROPERTY_MIN_HEIGHT = 'minHeight'
export const TOKEN_PROPERTY_MIN_WIDTH = 'minWidth'
export const TOKEN_PROPERTY_OPACITY = 'opacity'
export const TOKEN_PROPERTY_OUTLINE = 'outline'
export const TOKEN_PROPERTY_PADDING = 'padding'
export const TOKEN_PROPERTY_RADIUS = 'radius'
export const TOKEN_PROPERTY_RIGHT = 'right'
export const TOKEN_PROPERTY_SHADOW = 'shadow'
export const TOKEN_PROPERTY_SPACING = 'spacing'
export const TOKEN_PROPERTY_TEXT_DECORATION = 'decoration'
export const TOKEN_PROPERTY_TOP = 'top'
export const TOKEN_PROPERTY_TEXT_TRANSFORM = 'transform'
export const TOKEN_PROPERTY_WEIGHT = 'weight'
export const TOKEN_PROPERTY_WIDTH = 'width'

export const TOKEN_PROPERTIES = [
  TOKEN_PROPERTY_BACKGROUND,
  TOKEN_PROPERTY_BORDER,
  TOKEN_PROPERTY_BOTTOM,
  TOKEN_PROPERTY_COLOR,
  TOKEN_PROPERTY_FONT_FAMILY,
  TOKEN_PROPERTY_FONT_SIZE,
  TOKEN_PROPERTY_HEIGHT,
  TOKEN_PROPERTY_INDEX,
  TOKEN_PROPERTY_LEFT,
  TOKEN_PROPERTY_LINE_HEIGHT,
  TOKEN_PROPERTY_MARGIN,
  TOKEN_PROPERTY_MAX_HEIGHT,
  TOKEN_PROPERTY_MAX_WIDTH,
  TOKEN_PROPERTY_MIN_HEIGHT,
  TOKEN_PROPERTY_MIN_WIDTH,
  TOKEN_PROPERTY_OPACITY,
  TOKEN_PROPERTY_OUTLINE,
  TOKEN_PROPERTY_PADDING,
  TOKEN_PROPERTY_RADIUS,
  TOKEN_PROPERTY_RIGHT,
  TOKEN_PROPERTY_SHADOW,
  TOKEN_PROPERTY_SPACING,
  TOKEN_PROPERTY_TEXT_DECORATION,
  TOKEN_PROPERTY_TEXT_TRANSFORM,
  TOKEN_PROPERTY_TOP,
  TOKEN_PROPERTY_WEIGHT,
  TOKEN_PROPERTY_WIDTH,
]

/**
 * @since 1.0.2
 * @constant
 * @type {object}
 * @default
 */
export const VALID_DECLARATION_KEYS = {
  [TOKEN_CATEGORY_COLOR]: [
    TOKEN_PROPERTY_BACKGROUND,
    TOKEN_PROPERTY_BORDER,
    TOKEN_PROPERTY_OUTLINE,
    TOKEN_PROPERTY_COLOR,
  ],
  [TOKEN_CATEGORY_GLOBAL]: [],
  [TOKEN_CATEGORY_POSITION]: [
    TOKEN_PROPERTY_BOTTOM,
    TOKEN_PROPERTY_INDEX,
    TOKEN_PROPERTY_LEFT,
    TOKEN_PROPERTY_RIGHT,
    TOKEN_PROPERTY_TOP,
  ],
  [TOKEN_CATEGORY_SIZE]: [
    TOKEN_PROPERTY_BORDER,
    TOKEN_PROPERTY_HEIGHT,
    TOKEN_PROPERTY_MAX_HEIGHT,
    TOKEN_PROPERTY_MAX_WIDTH,
    TOKEN_PROPERTY_MIN_HEIGHT,
    TOKEN_PROPERTY_MIN_WIDTH,
    TOKEN_PROPERTY_OUTLINE,
    TOKEN_PROPERTY_RADIUS,
    TOKEN_PROPERTY_WIDTH,
  ],
  [TOKEN_CATEGORY_SPACE]: [
    TOKEN_PROPERTY_MARGIN,
    TOKEN_PROPERTY_OUTLINE,
    TOKEN_PROPERTY_PADDING,
  ],
  [TOKEN_CATEGORY_STYLE]: [
    TOKEN_PROPERTY_BORDER,
    TOKEN_PROPERTY_OPACITY,
    TOKEN_PROPERTY_SHADOW,
    TOKEN_PROPERTY_OUTLINE,
  ],
  [TOKEN_CATEGORY_TYPOGRAPHY]: [
    TOKEN_PROPERTY_TEXT_DECORATION,
    TOKEN_PROPERTY_FONT_FAMILY,
    TOKEN_PROPERTY_LINE_HEIGHT,
    TOKEN_PROPERTY_FONT_SIZE,
    TOKEN_PROPERTY_SPACING,
    TOKEN_PROPERTY_TEXT_TRANSFORM,
    TOKEN_PROPERTY_WEIGHT,
  ],
}

/**
 * @since 1.0.0
 * @constant
 * @type {object}
 * @default
 */
export const TOKEN_PROPERTY_CSS_MAP = {
  [`${TOKEN_CATEGORY_COLOR}:${TOKEN_PROPERTY_BACKGROUND}`]: 'background-color',
  [`${TOKEN_CATEGORY_COLOR}:${TOKEN_PROPERTY_BORDER}`]: 'border-color',
  [`${TOKEN_CATEGORY_COLOR}:${TOKEN_PROPERTY_OUTLINE}`]: 'outline-color',
  [`${TOKEN_CATEGORY_COLOR}:${TOKEN_PROPERTY_COLOR}`]: 'color',
  [`${TOKEN_CATEGORY_POSITION}:${TOKEN_PROPERTY_BOTTOM}`]: 'bottom',
  [`${TOKEN_CATEGORY_POSITION}:${TOKEN_PROPERTY_INDEX}`]: 'z-index',
  [`${TOKEN_CATEGORY_POSITION}:${TOKEN_PROPERTY_LEFT}`]: 'left',
  [`${TOKEN_CATEGORY_POSITION}:${TOKEN_PROPERTY_RIGHT}`]: 'right',
  [`${TOKEN_CATEGORY_POSITION}:${TOKEN_PROPERTY_TOP}`]: 'top',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_BORDER}`]: 'border-width',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_HEIGHT}`]: 'height',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_MAX_HEIGHT}`]: 'max-height',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_MAX_WIDTH}`]: 'max-width',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_MIN_HEIGHT}`]: 'min-height',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_MIN_WIDTH}`]: 'min-width',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_OUTLINE}`]: 'outline-width',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_RADIUS}`]: 'border-radius',
  [`${TOKEN_CATEGORY_SIZE}:${TOKEN_PROPERTY_WIDTH}`]: 'width',
  [`${TOKEN_CATEGORY_SPACE}:${TOKEN_PROPERTY_MARGIN}`]: 'margin',
  [`${TOKEN_CATEGORY_SPACE}:${TOKEN_PROPERTY_OUTLINE}`]: 'outline-offset',
  [`${TOKEN_CATEGORY_SPACE}:${TOKEN_PROPERTY_PADDING}`]: 'padding',
  [`${TOKEN_CATEGORY_STYLE}:${TOKEN_PROPERTY_BORDER}`]: 'border-style',
  [`${TOKEN_CATEGORY_STYLE}:${TOKEN_PROPERTY_OPACITY}`]: 'opacity',
  [`${TOKEN_CATEGORY_STYLE}:${TOKEN_PROPERTY_SHADOW}`]: 'box-shadow',
  [`${TOKEN_CATEGORY_STYLE}:${TOKEN_PROPERTY_OUTLINE}`]: 'outline-style',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_TEXT_DECORATION}`]: 'text-decoration',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_FONT_FAMILY}`]: 'font-family',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_LINE_HEIGHT}`]: 'line-height',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_FONT_SIZE}`]: 'font-size',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_SPACING}`]: 'letter-spacing',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_TEXT_TRANSFORM}`]: 'text-transform',
  [`${TOKEN_CATEGORY_TYPOGRAPHY}:${TOKEN_PROPERTY_WEIGHT}`]: 'font-weight',
}

/**
 * CSS properties that support length data types.
 * @see {@link https://developer.mozilla.org/en-US/docs/Web/CSS/length}
 */
export const TOKEN_PROPERTY_CSS_LENGTH = [
  TOKEN_PROPERTY_BOTTOM,
  TOKEN_PROPERTY_LEFT,
  TOKEN_PROPERTY_RIGHT,
  TOKEN_PROPERTY_TOP,
  TOKEN_PROPERTY_BORDER,
  TOKEN_PROPERTY_HEIGHT,
  TOKEN_PROPERTY_MAX_HEIGHT,
  TOKEN_PROPERTY_MAX_WIDTH,
  TOKEN_PROPERTY_MIN_HEIGHT,
  TOKEN_PROPERTY_MIN_WIDTH,
  TOKEN_PROPERTY_OUTLINE,
  TOKEN_PROPERTY_RADIUS,
  TOKEN_PROPERTY_WIDTH,
  TOKEN_PROPERTY_MARGIN,
  TOKEN_PROPERTY_OUTLINE,
  TOKEN_PROPERTY_PADDING,
  TOKEN_PROPERTY_FONT_SIZE,
  TOKEN_PROPERTY_SPACING,
]
