import { default as bindings } from './bindings'

export const {
  animationDelay,
  animationDuration,
  animationTimingFunction,
  backgroundColor,
  border,
  borderColor,
  borderRadius,
  borderStyle,
  borderWidth,
  bottom,
  boxShadow,
  color,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  height,
  left,
  letterSpacing,
  lineHeight,
  margin,
  marginBottom,
  marginLeft,
  marginRight,
  marginTop,
  maxHeight,
  maxWidth,
  minHeight,
  minWidth,
  opacity,
  padding,
  paddingBottom,
  paddingLeft,
  paddingRight,
  paddingTop,
  right,
  textAlign,
  textDecoration,
  textTransform,
  top,
  transitionDelay,
  transitionDuration,
  transitionTimingFunction,
  width,
  zIndex,
} = bindings

export { bindings }
