export { default as getHeadingLevelScale } from './getHeadingLevelScale'
export { default as getIntentColor } from './getIntentColor'
export { default as setHeadingFontSize } from './setHeadingFontSize'
export { default as setTextColor } from './setTextColor'
export { default as setTextFontSize } from './setTextFontSize'
