import getPropertyToTokenMap from '../src/getPropertyToTokenMap'

describe('getPropertyToTokenMap', () => {
  test('returns snake-case map', () => {
    expect(getPropertyToTokenMap()).toMatchInlineSnapshot(`
      Object {
        "animation-delay": "motion:delay",
        "animation-duration": "motion:duration",
        "animation-timing-function": "motion:effect",
        "background-color": "color:background",
        "border-color": "color:border",
        "border-radius": "size:radius",
        "border-style": "style:border",
        "border-width": "size:border",
        "bottom": "position:bottom",
        "color": "color:text",
        "font-family": "typography:font",
        "font-size": "size:text",
        "font-style": "style:text",
        "font-weight": "typography:weight",
        "height": "size:height",
        "left": "position:left",
        "letter-spacing": "typography:spacing",
        "line-height": "typography:lineHeight",
        "margin": "space:margin",
        "margin-bottom": "space:margin",
        "margin-left": "space:margin",
        "margin-right": "space:margin",
        "margin-top": "space:margin",
        "max-height": "size:maxHeight",
        "max-width": "size:maxWidth",
        "min-height": "size:minHeight",
        "min-width": "size:minWidth",
        "opacity": "style:opacity",
        "padding": "space:padding",
        "padding-bottom": "space:padding",
        "padding-left": "space:padding",
        "padding-right": "space:padding",
        "padding-top": "space:padding",
        "right": "position:right",
        "text-align": "position:text",
        "text-decoration": "typography:decoration",
        "text-transform": "typography:transform",
        "top": "position:top",
        "transition-delay": "motion:delay",
        "transition-duration": "motion:duration",
        "transition-timing-function": "motion:effect",
        "width": "size:width",
        "z-index": "position:index",
      }
    `)
  })

  test('returns camelCase map', () => {
    expect(getPropertyToTokenMap('camelCase')).toMatchInlineSnapshot(`
      Object {
        "animationDelay": "motion:delay",
        "animationDuration": "motion:duration",
        "animationTimingFunction": "motion:effect",
        "backgroundColor": "color:background",
        "borderColor": "color:border",
        "borderRadius": "size:radius",
        "borderStyle": "style:border",
        "borderWidth": "size:border",
        "bottom": "position:bottom",
        "color": "color:text",
        "fontFamily": "typography:font",
        "fontSize": "size:text",
        "fontStyle": "style:text",
        "fontWeight": "typography:weight",
        "height": "size:height",
        "left": "position:left",
        "letterSpacing": "typography:spacing",
        "lineHeight": "typography:lineHeight",
        "margin": "space:margin",
        "marginBottom": "space:margin",
        "marginLeft": "space:margin",
        "marginRight": "space:margin",
        "marginTop": "space:margin",
        "maxHeight": "size:maxHeight",
        "maxWidth": "size:maxWidth",
        "minHeight": "size:minHeight",
        "minWidth": "size:minWidth",
        "opacity": "style:opacity",
        "padding": "space:padding",
        "paddingBottom": "space:padding",
        "paddingLeft": "space:padding",
        "paddingRight": "space:padding",
        "paddingTop": "space:padding",
        "right": "position:right",
        "textAlign": "position:text",
        "textDecoration": "typography:decoration",
        "textTransform": "typography:transform",
        "top": "position:top",
        "transitionDelay": "motion:delay",
        "transitionDuration": "motion:duration",
        "transitionTimingFunction": "motion:effect",
        "width": "size:width",
        "zIndex": "position:index",
      }
    `)
  })
})
